---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: echo
  labels:
    app: echo
spec:
 replicas: 2
 selector:
   matchLabels:
     app: echo
     task: test
 template:
   metadata:
     labels:
       app: echo
       task: test
   spec:
     containers:
       - name: echo
         image: gcr.io/google_containers/echoserver:1.8
         ports:
           - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: echo
    task: test

---
apiVersion: v1
kind: Secret
metadata:
  name: house.local-ssl
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVWUxUbUFCUlFhaHNIbGc2UVJ2RkFzSDc5V2drd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dERVdNQlFHQTFVRUF3d05LaTVvYjNWelpTNXNiMk5oYkRBZUZ3MHhPVEF6TWpJd01EQTROVFphRncweQpNREF6TWpFd01EQTROVFphTUJneEZqQVVCZ05WQkFNTURTb3VhRzkxYzJVdWJHOWpZV3d3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURPR3E2UUxEalJhZXhka2ExdkIwdmVYU09Ed3VjUkJhU3cKM05aWFovMFdORnY3SmlsZ0xueExpRm4zWkswZDJXNTZVMVo1aER4WnNjNXRPRDlJczVNd1FlVThlWVpNT1YvRQovMEs4cENEYzIwMkhEYzNFNGcrWnBqVWk0Z242Z0JwUHg0TDdEOUNzR0pKSDRpTXJ4STBzU2hIVWxiazF6dld6ClBEcDIzeGY2dXJnM3NrZUJJZWE5V3pmQ0VOcDltdVN5bmZMWnYrdi92T1crd2NjMGxUM3NIOGxRcUhpdkNNK0MKOUJrcmJHQ1RLeXpXRjF0Z3NabGZaKzBpbjM2NVhmS2VIa2pPVHRONEFLQ2pBakxQMWkxa3hpYktJVjlVdSswdApkOFAxWHpMbTF1SVJFSk1uNkNZVng0dkxYZFNPKy90V2xDRU1SRlNzbjRhU09TcWozamVYQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCUlZRbnVPY1FjRnZSUDVPTmw1MkVEQ3RhallEekFmQmdOVkhTTUVHREFXZ0JSVlFudU8KY1FjRnZSUDVPTmw1MkVEQ3RhallEekFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFBZkFVMWhmcEtqVmVVenFvaWpGTHFFQU4rN1pocUZENE1QcHc0T3ArT1lQSXF6WWJxeHp4NGJoK0NFCi9XNWVSTG5EVkhEaUJabUhRay9zckVkNGxFZTNRczdRanJlbURkZkxJNHhiZ25CQTJDYUFqbW9vMFRTWkx3V1UKTVpJTS9hUUt5NUJTSXB5YkdoODJhTy9EREphWlJtcWIyd1VNR29TZDBzaGk5MDFrUW1qU05GQnQ1QjNsODVYcgoxc2Y4b0NibDg5RDFqOVUyWjVsd1NvbmZCNUVhbVZ4c2hsNGtVZ25vQzZEMmcxVDVuTG1ZYWRoNUFVK0FzczUvCnV0cG40dm9aNllNdE5adTRMYTNlQXUwNFVsMkw2T0JHNjlPUCtJdGk4ZU5JdzJMd2ovcmh5K2xoMlBTTkF5czkKejhaaTJvQlpEektFTkZQRFc1MEYxZXluN3UrWAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRE9HcTZRTERqUmFleGQKa2ExdkIwdmVYU09Ed3VjUkJhU3czTlpYWi8wV05GdjdKaWxnTG54TGlGbjNaSzBkMlc1NlUxWjVoRHhac2M1dApPRDlJczVNd1FlVThlWVpNT1YvRS8wSzhwQ0RjMjAySERjM0U0ZytacGpVaTRnbjZnQnBQeDRMN0Q5Q3NHSkpICjRpTXJ4STBzU2hIVWxiazF6dld6UERwMjN4ZjZ1cmczc2tlQkllYTlXemZDRU5wOW11U3luZkxadit2L3ZPVysKd2NjMGxUM3NIOGxRcUhpdkNNK0M5QmtyYkdDVEt5eldGMXRnc1psZlorMGluMzY1WGZLZUhrak9UdE40QUtDagpBakxQMWkxa3hpYktJVjlVdSswdGQ4UDFYekxtMXVJUkVKTW42Q1lWeDR2TFhkU08rL3RXbENFTVJGU3NuNGFTCk9TcWozamVYQWdNQkFBRUNnZ0VCQUp4K2dnR1NzbW5BQmV0ZVM5UThOQTFacHpmSzYreHUzb2cwaHNQRGY5WTIKVjRreGhzVXpSc21MZE5SMkswUzQ3andQdjE5eFd1bTRLc2VmcDkycURKN2R5aFBMS29BQ0tJZktVb0F1RjQzYgpMdGpYVUdDb1RiUWJFY20wM0dMS2xpL3hpN0RhWjFYbEtsMU9oZW9ieWgzUStBejB5cmJpdUlrcHVESytYdFRQClNERG5XTllQQVB5ajYxWDd6M09kR3MvWHdyOVBJTCtMZ2FnYjNlMitIY3crM2xhNVcyUVRrUmM1dkVKOW5KY1gKZk1ILzNEcDljUS9zL3FRUENkbTRqbXpGU2RJTHB5dXErTXJwWFhhR2xYclh5aVRGVEEzYld1dy9FNGdDdnBjbQpDckxpYzhaRFpoZVJldnd4emVMNytLRUg0blZCSkpLWGdOMjVnN0llQ0dFQ2dZRUErZ0c4YW04aDFJZ0FlSkRVCmpCbjNWZ1o4bENNbXNkaEo5dXdzWUFScmlSZy8xT2k1MFdNYXZrcGNEa2xyd0lJMk9GbVVKWTFTMEVvcjBCSVkKcXFIM2dzRGdUVFlhcTdQOTZPVmpzL0NZL093RGRpV1NKSHkyaVlBL3pJZWVFU0FDQkpmYXJiTnhXLzM4NFovdApyWWthNkd0ZEM0bEdHNzZPdVFBWU80RXRjZjhDZ1lFQTB3dUZVRlNhQlFwVTVIMklZQ0ZnQWd4UENpbkxaL3p2CkFHQ24vcnlKQVZXb0VvRGFqRnBKMXNQc1IrKzZoVm81YUluU3czRDZmYWhnamQ0U09WZGYrWWpBSXFKa2ZKZHEKM3VRTzFDWEtVQnBjNkFrb1hlSFVXUnlsOGs4OFpBbko5YWg0Mzhnek1HUW9uRXFoVlZSZjRKSFhyVTh6VGRsSwpzNjFzWURrNWlta0NnWUJoTytXYys2WUxzKzJDOXNsRHlDR1RPcWlmTU9DdTBMRkxzT1U5WHRxNEVrOVpMajUrCittMS9Ud3Bvb0JPaFpzTlJ2VDFLTWFIZzBzZ2hmN2hLUFA0M3cyNDVlVzU4RTJBUWdZNzZmL3Z3ZXBhS0QraTcKK2lsQVp6bnBBV0h2eFNRanh5L00yUHFnemJMWnljcTE4Sm9maFFwR0gxaStGNm9JdDhtMDh2UEszd0tCZ0ZVUgpzc1lqcEFYZUdVUVUrZERPQXpZd0lmZ1Z5c0Q2NnBmN1hoeEhnTzVCeWNMVG44U3RiRkFlbjNLTHhtS1VjTW1iCnJKSk5TeHMxc04zZW92ZnNLV3FiWGQ5WUdDdEVtYmFJdFJWOHVpVTV5ek5ZNWFXYUx3OVFoZSs3VXJ0OFdxVWsKS0wwRHBPYWZxT0wvRGpNb0ZKR2dHQkRxK09JcmNYb2xzS2JFeWxYcEFvR0JBSmhaeG43aGNtMmpTZ2JPZ3YyaApDQldQVE9Ra1hWT0lzZGxLRnZDdkpUbkM3RmxEOXBYVFdOL1A0Wks2TGlKcTNSMGg2VCtxc3Zvc1l5Wmc3M2w1ClZFUGVjVFFtZVJrZUhOM05DeFNSVkhvZXczMnU3bWY0WlM3WUx2emh0M0JZMEhVK2FlOXEway9nenIvYm5jdGkKajBRcTJlYStFcEtIZ1kwZkhweVdpamovCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: echo.house.local
      http:
        paths:
          - path: /
            backend:
              serviceName: echo
              servicePort: http
  tls:
    - secretName: house.local-ssl

